### ISSUE TITLE
Error when using an invalid method name as parameter when storing a template

### ISSUE THREAD

**Issue by editf** [sanredz/DD2480-httpie#11]
Trying to store a template with an invalid method causes the following error in `store_json_template`: 
```
>           variable_name, variable_value = arg.split("=")
E           ValueError: not enough values to unpack (expected 2, got 1)

httpie/cli/argtemplate.py:24: ValueError
```
The args passed were `test_template NOT_VALID_METHOD https://catfact.ninja/fact param1=value1 param2=value2`

**Comment by mrporsev** [comment]
done
